# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile_num', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_years', models.IntegerField(max_length=2)),
                ('job_designation', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=300)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_percent', models.DecimalField(decimal_places=1, max_digits=3)),
                ('inter_percent', models.DecimalField(decimal_places=1, max_digits=3)),
                ('degree_percent', models.DecimalField(decimal_places=1, max_digits=3)),
                ('college_name', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('B.Tech/B.E', 'Btech'), ('B.com', 'Bcom'), ('Bsc', 'Bsc'), ('M.Tech', 'Mtech'), ('Msc', 'Msc'), ('B.A.', 'BA'), ('M.B.A', 'MBA'), ('B.B.A', 'BBA')], max_length=10)),
                ('branch', models.CharField(max_length=15)),
                ('skills', models.CharField(max_length=300)),
                ('interests', models.CharField(max_length=300)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserDetails')),
            ],
        ),
    ]
