# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='no_of_years',
            field=models.IntegerField(),
        ),
    ]
