# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170313_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_num',
            field=models.IntegerField(),
        ),
    ]
