# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170315_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_num',
            field=models.CharField(max_length=15),
        ),
    ]
