# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170315_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='degree_percent',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inter_percent',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ssc_percent',
            field=models.CharField(max_length=5),
        ),
    ]
