# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170322_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(choices=[('Btech', 'Btech'), ('Bcom', 'Bcom'), ('Bsc', 'Bsc'), ('Mtech', 'Mtech'), ('Msc', 'Msc'), ('BA', 'BA'), ('MBA', 'MBA'), ('BBA', 'BBA')], max_length=10),
        ),
    ]
