# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170313_1930'),
        ('jobs', '0007_auto_20170315_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserDetails')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs')),
            ],
        ),
    ]
