# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20170315_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience_required',
            field=models.IntegerField(),
        ),
    ]
