# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20170410_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=15),
        ),
    ]
