# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20170410_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience_required',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
