# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170302_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='title',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='id',
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Questions'),
        ),
    ]
