# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teststaken_marks_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_choice',
            field=models.CharField(max_length=1000),
        ),
    ]
