# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170313_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.CharField(max_length=1000)),
                ('correct_choice', models.IntegerField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tests')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set([('test_id', 'question_id')]),
        ),
    ]
