# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170313_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
