# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170313_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='choices',
            name='choice_id',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='test_id',
        ),
    ]
