# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170313_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsapplied',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobsapplied',
            name='job_id',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='JobsApplied',
        ),
    ]
