# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170315_1541'),
        ('users', '0018_auto_20170313_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id_selected', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserDetails')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Questions')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tests')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together=set([('email', 'test_id', 'question_id')]),
        ),
    ]
