# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20170317_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='choice_id_selected',
            field=models.CharField(max_length=1000),
        ),
    ]
